enum komainf{
    empty = 0,
    fu = 1,
    kyosya,
    keima,
    gin,
    kin,
    kaku,
    hisya,
    gyoku,
    tokin,
    nari_kyou,
    nari_kei,
    nari_gin,
    dummy,
    uma,
    ryu,
    promoted = tokin - fu,
    koma_mask = 0x0f,
    own_mask = 0x10,
    own_fu = fu + own_mask,
    own_kyosya,
    own_keima,
    own_gin,
    own_kin,
    own_kaku,
    own_hisya,
    own_gyoku,
    own_tokin,
    own_nari_kyou,
    own_nari_kei,
    own_nari_gin,
    own_dummy,
    own_uma,
    own_ryu,
    opponent_mask = 0x20,
    opp_fi = fu + opponent_mask,
    opp_kyosya,
    opp_keima,
    opp_gin,
    opp_kin,
    opp_kaku,
    opp_hisya,
    opp_gyoku,
    opp_tokin,
    opp_nari_kyou,
    opp_nari_kei,
    opp_nari_gin,
    opp_uma,
    opp_ryu,
    wall = 0x80
    };

typedef unsigned char komainf;
inline int is_enemy